apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe
          image: tic-tac-toe:latest
          imagePullPolicy: IfNotPresent
          # Note: The pipeline will update this tag automatically
          # image: your-docker-username/vite-app:latest
          ports:
            - containerPort: 80
