name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Use the GitHub Run ID so every image has a unique tag
          tags: ${{ secrets.DOCKER_USERNAME }}/vite-app:${{ github.run_id }}
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set GKE Context
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Deploy to K8s
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/vite-app:${{ github.run_id }}|" deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Rollout
        run: kubectl rollout status deployment/vite-app --timeout=120s